-- AlterTable
ALTER TABLE "User" ADD COLUMN     "avatarPosX" DOUBLE PRECISION DEFAULT 50,
ADD COLUMN     "avatarPosY" DOUBLE PRECISION DEFAULT 50,
ADD COLUMN     "avatarZoom" DOUBLE PRECISION DEFAULT 1,
ADD COLUMN     "bannerPosX" DOUBLE PRECISION DEFAULT 50,
ADD COLUMN     "bannerPosY" DOUBLE PRECISION DEFAULT 50,
ADD COLUMN     "bannerZoom" DOUBLE PRECISION DEFAULT 1;
